### PR TITLE
neolib event system refactored for performance and QoI.

### PR DESCRIPTION
**Pull request by i42output**
Hi Matt,

neolib event has moved up the list a tad! :D

/Leigh

### CODE REVIEW

**Comment by NoAvailableAlias** [comment]
Thanks for the PR!
Sweet, I'll get this merged and the results updated after work.
My plan is to squash this particular PR merge due to the lib improvements being done inline.

**Comment by i42output** [comment]
it isn't ready to be merged to master: there is an issue with the "thread object" that needs resolving; a thread object needs to be associated with the thread using the event.

**Comment by NoAvailableAlias** [comment]
Hmm, that might require an optional function trait injected into the Benchmark::threaded function via the trait class.

I'll postpone the merge.

Edit: Oic thought you meant the benchmark thread needed to do something explicit with the benchmark class.

**Comment by NoAvailableAlias** [comment]
Let me know when this PR is good to go!
(I must now add even more benchmark libs due to reddit...)

**Comment by i42output** [comment]
Hopefully I will get a chance to look at it this week.

**Pull request closed without merging**
